# This is a config for E2B sandbox template.
# You can use template ID (l60wwui5kwgiqnr1b6kq) or template name (webify-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("webify-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("webify-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('webify-nextjs-test2')

team_id = "33f9008f-a6d6-44e5-84af-e1161bcd22b4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "webify-nextjs-test2"
template_id = "l60wwui5kwgiqnr1b6kq"
